# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_helloextendr_wrappers", use_symbols = TRUE, package_name = "helloextendr")

#' @docType package
#' @usage NULL
#' @useDynLib helloextendr, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

VecUsize <- new.env(parent = emptyenv())

VecUsize$new <- function(robj) .Call(wrap__VecUsize__new, robj)

VecUsize$subset <- function(idx) .Call(wrap__VecUsize__subset, self, idx)

VecUsize$length <- function() .Call(wrap__VecUsize__length, self)

VecUsize$to_text <- function() .Call(wrap__VecUsize__to_text, self)

#' @export
`$.VecUsize` <- function (self, name) { func <- VecUsize[[name]]; environment(func) <- environment(); func }

#' @export
`[[.VecUsize` <- `$.VecUsize`

